#!/usr/bin/env php
<?php
/**
 * Created by PhpStorm.
 * User: mcurry
 * Date: 9/28/17
 * Time: 2:11 PM
 */

// include requirements
include '../bootstrap.php';
require_once '../vendor/simpletest/simpletest/autorun.php';

// include all tests
include 'user_test.php';
//include 'cache_test.php';
